# Generated by Django 4.0.5 on 2022-06-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('animal_type', models.CharField(max_length=50)),
                ('coordinates', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('threat_level', models.CharField(max_length=50)),
                ('_image', models.TextField(blank=True, db_column='image')),
                ('text', models.CharField(max_length=2000)),
                ('remaining_animals_numbers', models.IntegerField()),
                ('cause_danger', models.CharField(max_length=300)),
                ('habitat', models.CharField(max_length=200)),
            ],
        ),
    ]
