# Generated by Django 4.0.5 on 2022-06-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiere', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animals',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='animals',
            old_name='longitude',
            new_name='lng',
        ),
    ]
